---
title: "World Cup data analysis"
output: html_notebook
---

```{r}
source("WorldCup.R")
```

```{r}
setwd("./db")
countries <- read.csv2("teams.csv", sep = ',')
games <- read.csv2("games.csv", sep=',')

# Adds a column containing World Cup edition (year)
games <- cbind(games, getYearsFromDates(games$play_at))
colnames(games)[length(games)] <- "year"

# Creates a human readabe data set
gamesId <- games$id
team1HumanReadable <- countries$title[games$team1_id]
team2HumanReadable <- countries$title[games$team2_id]

humanReadable <- data.frame(gamesId, team1HumanReadable, team2HumanReadable, games$score1, games$score2, games$score1et, games$score2et, games$score1p, games$score2p, games$winner, games$play_at, games$year)
humanReadable <- humanReadable[which(!is.na(humanReadable$games.winner)),]

# Come on, West Germany should be Germany!
humanReadable$team1HumanReadable <- gsub("West Germany \\(-1989\\)", "Germany", humanReadable$team1HumanReadable)
humanReadable$team2HumanReadable <- gsub("West Germany \\(-1989\\)", "Germany", humanReadable$team2HumanReadable)

# Soviet Union -> Russia
humanReadable$team1HumanReadable <- gsub("Soviet Union \\(-1991\\)", "Russia", humanReadable$team1HumanReadable)
humanReadable$team2HumanReadable <- gsub("Soviet Union \\(-1991\\)", "Russia", humanReadable$team2HumanReadable)

# Let's create stats for all countries which have ever participated to the World Cup

# First let's get al participants
allParticipants <- getAllTimeParticipants(humanReadable)

# Builds stats for all the participants
stats <- data.frame()

for (i in 1:length(allParticipants)) {
    stats <- rbind(stats, getStats(humanReadable, allParticipants[i]))
}

```


# World Cup tournaments stats

## Appearances

```{r}

top10Appearances <- stats[head(order(-stats$Appearances), 10),]

appearances <- top10Appearances$Appearances
names(appearances) <- top10Appearances$Country
barplot(appearances, las = 2)

```

## Games played

```{r}

top10GamesPlayed <- stats[head(order(-stats$`Number of games played`), 10),]

gamesPlayed <- top10GamesPlayed$`Number of games played`
names(gamesPlayed) <- top10GamesPlayed$Country
barplot(gamesPlayed, las = 2)

```

## Wins

```{r}

top10Wins <- stats[head(order(-stats$Wins), 10),]

wins <- top10Wins$Wins
names(wins) <- top10Wins$Country
barplot(wins, las = 2)

```

# Draws

```{r}

top10Draws <- stats[head(order(-stats$Draws), 10),]

draws <- top10Draws$Draws
names(draws) <- top10Draws$Country
barplot(draws, las = 2)

```

# Losses

```{r}

top10Losses <- stats[head(order(-stats$Losses), 10),]

losses <- top10Losses$Losses
names(losses) <- top10Losses$Country
barplot(losses, las = 2)

```
## Wins per attendance

```{r}

winRate <- stats
winRate$Wins <- round(winRate$Wins/winRate$Appearances, 2)

top10WinRate <- winRate[head(order(-winRate$Wins), 10),]

winRates <- top10WinRate$Wins
names(winRates) <- top10WinRate$Country
barplot(winRates, las = 2)

```

# Draws per attendance

```{r}

drawRate <- stats
drawRate$Draws <- round(drawRate$Draws/drawRate$Appearances, 2)

top10drawRate <- drawRate[head(order(-drawRate$Draws), 10),]

drawRates <- top10drawRate$Draws
names(drawRates) <- top10drawRate$Country
barplot(drawRates, las = 2)

```

# Losses per attendance

```{r}

lossRate <- stats
lossRate$Losses <- round(lossRate$Losses/lossRate$Appearances, 2)

top10LossRate <- lossRate[head(order(lossRate$Losses), 10),]

lossRates <- top10LossRate$Losses
names(lossRates) <- top10LossRate$Country
barplot(lossRates, las = 2)

```

# All finals

## Games
```{r}
worldCupEditions <- unique(humanReadable$games.year)

finals <- data.frame()

for (year in worldCupEditions) {
    finals <- rbind(finals, tail(getGamesPerYear(humanReadable, year), 1))
}

print(finals)
```

## Final participants

```{r}

finalists <- unique(c(finals$team1HumanReadable, finals$team2HumanReadable))

print(finalists)

```
